### ISSUE TITLE
No propper release for 1.3

### ISSUE THREAD

**Issue by kakulukia** [alsoicode/django-maintenancemode-2#16]
I cant install that latest version 1.3 and am getting the following errors:

`pip install django-maintenancemode-2` is installing version 1.2
`pip install django-maintenancemode-2==1.3` is giving the following output:

    ERROR: Could not find a version that satisfies the requirement django-maintenancemode-2==1.3 (from versions: 1.3.macosx-10.9-x86_64, 1.1, 1.1.2, 1.1.3, 1.1.4, 1.1.5, 1.1.6, 1.1.7, 1.1.8, 1.1.9, 1.1.10, 1.1.11, 1.2)
    ERROR: No matching distribution found for django-maintenancemode-2==1.3

and finally when i try to install that weird 1.3.macosx-10.9-x86_64 version i get this:

    ERROR: File "setup.py" not found for legacy project django-maintenancemode-2==1.3.macosx-10.9-x86_64 from https://files.pythonhosted.org/packages/e4/98/81ab7a34519e7afd784b2c22d3b69de1bee18862bdf4f03618f72d4499bd/django-maintenancemode-2-1.3.macosx-10.9-x86_64.tar.gz#sha256=7d6eb331bdffc88b04290138d81a8bc695c28c7e6111b6cd93097939b46e4203.

On top the 1.3 release is not tagged and thus not visible in GitHub. (but that sure does not mean anything other than that)

**Comment by alsoicode** [comment]
Hello. I have deployed a wheel for 1.3 and also pushed the 1.3 tag to Github. Please try installing from the wheel. If that doesn't work, I'll do a version bump to 1.3.1 and re-deploy to PyPi.

**Comment by kakulukia** [comment]
The above errors sadly are still present .. how do you install that version and how come its working that way?

**Comment by alsoicode** [comment]
Hmm. I'm not sure what went wrong with the previous release, but I bumped the version to 1.3.1 and was able to install that version by running: `pip3 install django-maintenancemode-2`

Output:

```
Collecting django-maintenancemode-2
  Downloading django-maintenancemode-2-1.3.1.tar.gz (18 kB)
Collecting django
  Downloading Django-3.2.5-py3-none-any.whl (7.9 MB)
     |████████████████████████████████| 7.9 MB 2.7 MB/s 
Collecting pytz
  Downloading pytz-2021.1-py2.py3-none-any.whl (510 kB)
     |████████████████████████████████| 510 kB 2.3 MB/s 
Collecting asgiref<4,>=3.3.2
  Downloading asgiref-3.4.1-py3-none-any.whl (25 kB)
Collecting sqlparse>=0.2.2
  Downloading sqlparse-0.4.1-py3-none-any.whl (42 kB)
     |████████████████████████████████| 42 kB 3.4 MB/s 
Building wheels for collected packages: django-maintenancemode-2
  Building wheel for django-maintenancemode-2 (setup.py) ... done
  Created wheel for django-maintenancemode-2: filename=django_maintenancemode_2-1.3.1-py3-none-any.whl size=22493 sha256=3b1bd02af03e00563d9357ef83f6ffaeac75db207ff088400d0b70048ec93b3d
  Stored in directory: /Users/btaylor/Library/Caches/pip/wheels/9b/61/26/cba1137284ec1b74fdcc61a98716b8adf7c0c7a07494dc838a
Successfully built django-maintenancemode-2
```

**Comment by kakulukia** [comment]
Thx, this also works for me again.
